package dao;

import dao.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

import domain.model.Client;

public class ClientRepository extends RepositoryBase<Client>{
	
    public ClientRepository(Connection connection, IMapResultSetIntoEntity<Client> mapper) {
        super(connection, mapper);
    }

    @Override
	protected String createTableSql() {
		return "" + "CREATE TABLE client("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20),"
				+ "surname varchar(50),"
				+ "passportNumber varchar(9)"
		        + ")";
	}
    
    @Override
    protected String tableName() {
        return "client";
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO client(name, surname, passportNumber) VALUES ('Jan', 'Kowalski', '123456789')";
    }

    @Override
    protected String updateSql() {
        return "UPDATE CLIENT SET (name, surname, passportNumber)= (?,?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(Client entity) throws SQLException {
        update.setString(1, entity.getName());
        update.setString(2, entity.getSurname());
        update.setString(3, entity.getPassportNumber());
    }

    @Override
    protected void setInsert(Client entity) throws SQLException {
        insert.setString(1, entity.getName());
        insert.setString(2, entity.getSurname());
        insert.setString(3, entity.getPassportNumber());	
	}
}	
