package dao;

import dao.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

import domain.model.Client;

public class ClientRepository extends RepositoryBase<Client>{
	
    public ClientRepository(Connection connection, IMapResultSetIntoEntity<Client> mapper) {
        super(connection, mapper);
    }

    @Override
	protected String createTableSql() {
		return "" + "CREATE TABLE client("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + "passportNumber varchar(9),"
				+ "FOREIGN KEY (PAYMENT_ID) REFERENCES payment(id),"
		        + "FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee(id),"
		        + "FOREIGN KEY (TOUR_ID) REFERENCES tour(id)," + ")";		
	}

    @Override
    protected String tableName() {
        return "client";
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO history("
                + "name, surname, passportNumber,"
                + "PAYMENT_ID,"
                + "EMPLOYEE_ID,"
                + "TOUR_ID"
                + ") VALUES (?,?,?,?,?,?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE CLIENT SET (name, surname, passportNumber, PAYMENT_ID" +
                ", EMPLOYEE_ID, TOUR_ID)= (?,?,?,?,?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(Client entity) throws SQLException {
        update.setString(1, entity.getName());
        update.setString(2, entity.getSurname());
        update.setString(3, entity.getPassportNumber());
        update.setInt(4, entity.getPayment().getId());
        update.setInt(5, entity.getEmployee().getId());
        update.setInt(6, entity.getTour().getId());
    }

    @Override
    protected void setInsert(Client entity) throws SQLException {
        insert.setString(1, entity.getName());
        insert.setString(2, entity.getSurname());
        insert.setString(3, entity.getPassportNumber());
        insert.setInt(4, entity.getPayment().getId());
        insert.setInt(5, entity.getEmployee().getId());
        insert.setInt(6, entity.getTour().getId());	
	}
}	
