package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import domain.model.Employee;

public class EmployeeRepository extends RepositoryBase{
	
	String insertSql = "INSERT INTO employee(name, surname, identityNumber) VALUES (?,?,?)";
	String selectByIdSql = "SELECT * FROM employee WHERE id=?";
	String updateByIdSql = "UPDATE employee SET NAME=? WHERE id=?";
	String deleteByIdSql = "DELETE FROM employee where id=?";
	String getAllSql = "SELECT * FROM employee";
	
	PreparedStatement insert;
	PreparedStatement selectById;
	PreparedStatement updateById;
	PreparedStatement deleteById;
	static PreparedStatement getAll; 
	
	public EmployeeRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);
			updateById = connection.prepareStatement(updateByIdSql);
			deleteById = connection.prepareStatement(deleteByIdSql);
			getAll = connection.prepareStatement(getAllSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Employee get(int employeeId){
		try{
			selectById.setInt(1, employeeId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				Employee result = new Employee();
				result.setId(rs.getInt("id"));
				result.setName(rs.getString("name"));
				result.setSurname(rs.getString("surname"));
				result.setIdentityNumber(rs.getString("identityNumber"));
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
	}
	
	public void add(Employee employee) {
		try {
			insert.setString(1, employee.getName());
			insert.setString(2, employee.getSurname());
			insert.setString(3, employee.getIdentityNumber());
			insert.executeUpdate();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}
	
	public void update(Employee employee){
		 try {
			updateById.setString(1, employee.getName());
		    updateById.setString(2, employee.getSurname());
		    updateById.setString(2, employee.getIdentityNumber());
		} catch (SQLException e) {
		      e.printStackTrace();
		}
}
	
	public void delete(Employee employee){
		try{
		    deleteById.setInt(1, employee.getId());
		}catch(Exception e) {
			  e.printStackTrace();
		}
}
	
	public static List <Employee> getAll(){
		List <Employee> list = new ArrayList<Employee>();
		try{
			ResultSet rs = getAll.executeQuery();
			while(rs.next()){
				Employee result = new Employee();
				result.setId(rs.getInt(1));
				result.setName(rs.getString(2));
				result.setSurname(rs.getString(3));
				result.setIdentityNumber(rs.getString(4));
				list.add(result);
			}
	}catch(Exception e)
		{e.printStackTrace();}
		return list;
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE employee("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + "identityNumber varchar(9),"
				+ "FOREIGN KEY (PAYMENT_ID) REFERENCES payment(id),"
		        + "FOREIGN KEY (CLIENT_ID) REFERENCES employee(id),"
		        + "FOREIGN KEY (TOUR_ID) REFERENCES tour(id)," + ")";		
	}

	@Override
	protected String tableName() {
		return "client";
	}
}


