package dao;

import dao.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

import domain.model.Hotel;

public class HotelRepository extends RepositoryBase<Hotel>{
	
    public HotelRepository(Connection connection, IMapResultSetIntoEntity<Hotel> mapper) {
        super(connection, mapper);
    }

	    @Override
		protected String createTableSql() {
			return "CREATE TABLE hotel("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
					+ "name varchar(20),"
					+ "FOREIGN KEY (TOUR_ID) REFERENCES tour(id)," + ")";
		}

	    @Override
	    protected String tableName() {
	        return "hotel";
	    }

	    @Override
	    protected String insertSql() {
	        return "INSERT INTO hotel("
	                + "name,"
	                + "TOUR_ID"
	                + ") VALUES (?,?)";
	    }

	    @Override
	    protected String updateSql() {
	        return "UPDATE HOTEL SET (name" +
	                ", TOUR_ID)= (?,?) WHERE id = ?";
	    }

	    @Override
	    protected void setUpdate(Hotel entity) throws SQLException {
	        update.setString(1, entity.getName());
	        update.setInt(6, entity.getTour().getId());
	    }

	    @Override
	    protected void setInsert(Hotel entity) throws SQLException {
	        insert.setString(1, entity.getName());
	        insert.setInt(6, entity.getTour().getId());	
		}
	}	


