package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import domain.model.Hotel;

public class HotelRepository extends RepositoryBase{
	
	String insertSql = "INSERT INTO hotel(Id) VALUES (?)";
	String selectByIdSql = "SELECT * FROM hotel WHERE id=?";
	String updateByIdSql = "UPDATE hotel SET ID=? WHERE id=?";
	String deleteByIdSql = "DELETE FROM hotel where id=?";
	String getAllSql = "SELECT * FROM hotel";
		
	PreparedStatement insert;
	PreparedStatement selectById;
	PreparedStatement updateById;
	PreparedStatement deleteById;
	static PreparedStatement getAll; 
	
	public HotelRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);
			updateById = connection.prepareStatement(updateByIdSql);
			deleteById = connection.prepareStatement(deleteByIdSql);
			getAll = connection.prepareStatement(getAllSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void update(Hotel hotel){
		 try {
			updateById.setInt(1, hotel.getId());
		} catch (SQLException e) {
		      e.printStackTrace();
		}
}
	
	public void delete(Hotel hotel){
		try{
		    deleteById.setInt(1, hotel.getId());
		}catch(Exception e) {
			  e.printStackTrace();
		}
}
	
	public static List <Hotel> getAll(){
		List <Hotel> list = new ArrayList<Hotel>();
		try{
			ResultSet rs = getAll.executeQuery();
			while(rs.next()){
				Hotel result = new Hotel();
				result.setId(rs.getInt(1));
				result.setName(rs.getString(2));
				list.add(result);
			}
	}catch(Exception e)
		{e.printStackTrace();}
		return list;
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE hotel("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
				+ "name varchar(20),"
				+ "FOREIGN KEY (TOUR_ID) REFERENCES tour(id)," + ")";
	}

	@Override
	protected String tableName() {
		return "hotel";
	}
}

